- name: Set repositories (debian)
  template: src=debian dest=/etc/apt/sources.list
  when: ansible_distribution == 'Debian'
- name: Set repositories (ubuntu)
  template: src=ubuntu dest=/etc/apt/sources.list
  when: ansible_distribution == 'Ubuntu'

- name: Update repositories (ubuntu & debian)
  apt: update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Update repositories (fedora & CentOS)
  shell: yum update -y
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'
- name: Update repositories (FreeBSD)
  shell: pkg update
  when: ansible_distribution == 'FreeBSD'

- name: Upgrade packages (ubuntu & debian)
  apt: upgrade=dist
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Upgrade packages (fedora & CentOS)
  yum: name=* state=latest
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'
- name: Upgrade packages (FreeBSD)
  shell: pkg upgrade -y
  when: ansible_distribution == 'FreeBSD'
