- name: Set hostname (Debian & Ubuntu & CentOS)
  hostname: name={{ inventory_hostname | lower }}
  when: ansible_os_family == 'Debian' or ansible_distribution == 'CentOS'
- name: Set hostname (FreeBSD)
  lineinfile: dest=/etc/rc.conf regexp=^hostname=
    line='hostname={{ inventory_hostname | lower }}'
  when: ansible_distribution == 'FreeBSD'
