- name : Restart service
  service: name=ntp state=restarted
  when: ansible_os_family == 'Debian'
- name : Restart service
  service: name=ntpd state=restarted
  when: ansible_os_family !== 'Debian'
